//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpprojectTask
    {
        public int project_ID { get; set; }
        public int Empno { get; set; }
        public Nullable<System.DateTime> Started_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Task { get; set; }
        public string Status { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblproject tblproject { get; set; }
    }
}
