//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblproject()
        {
            this.tblEmpprojectTasks = new HashSet<tblEmpprojectTask>();
        }
    
        public int project_ID { get; set; }
        public string descr { get; set; }
        public Nullable<System.DateTime> Started_Date { get; set; }
        public Nullable<System.DateTime> planned_end_Date { get; set; }
        public Nullable<System.DateTime> Actual_end_Date { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<int> client_ID { get; set; }
    
        public virtual tblclient tblclient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpprojectTask> tblEmpprojectTasks { get; set; }
    }
}
